language: php
sudo: false

env:
  global:
    - SYMFONY_VERSION="2.8.x"


matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.3

services:
  - mysql

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - composer install -n

before_script:
  - php app/console doctrine:schema:create -n --env test
  - php app/console doctrine:fixtures:load -n --env test

script:
  - php bin/codecept run -c src/AppBundle/
  
