language: php

sudo: true

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
    - ./vendor/codeception

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  - wget https://get.symfony.com/cli/installer -O - | bash
  - export PATH="$HOME/.symfony/bin:$PATH"

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction
  - symfony server:ca:install --no-interaction --quiet

script:
  - symfony serve -d
  - vendor/bin/codecept run --colors
