language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update
  - ./bin/console server:start
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
